// ============================================================================
//  INTERNATIONALISATION
// ============================================================================
export const STRINGS = {
  fr: {
    appSub: "dimensionnement sécheur à bande",
    appTag: "Bilan matière & enthalpie · zone chaude 4 passes + zone finale 4 passes · pré-chauffeur, condenseur, huile thermique",
    runAuto: "Pré-dimensionner (auto)", runUser: "Calculer · modèle imposé",
    computing: "Calcul…", reset: "Réinitialiser",
    save: "Sauver", load: "Charger", report: "Rapport PDF",
    langBtn: "EN", langTitle: "Switch to English",
    errTitle: "Le calcul a échoué.",
    loadErr: "Fichier de projet illisible ou incompatible.",
    loadOk: "Projet chargé — relancez le calcul.",
    savedOk: "Projet enregistré.",
    reportBlocked: "La fenêtre d'impression a été bloquée : le rapport a été téléchargé en HTML. Ouvrez-le puis imprimez-le en PDF.",
    noRunTitle: "Aucun calcul lancé",
    noRunBody: "Renseignez les onglets 1 à 3 puis lancez « Pré-dimensionner » pour laisser l'outil choisir le modèle de sécheur, ou « Modèle imposé » pour vérifier une machine donnée.",
    reportNeedsRun: "Lancez d'abord un calcul pour produire un rapport.",
    tabBasis: "1 · Données de base", tabSetpoints: "2 · Consignes", tabEquip: "3 · Paramètres équipement",
    tabSummary: "Synthèse", tabBalance: "Bilan matière & enthalpie",
    tabBelt: "Bandes & transfert", tabEquipment: "Ventilateurs & chauffe",
    modeAuto: "Pré-sélection automatique", modeUser: "Modèle imposé",
    liveOn: "mise à jour auto", liveUpdating: "recalcul…",
    modeLabel: "Mode :",

    secProject: "Projet", secLoad: "Charge de boue", secLoadNote: "entrées primaires",
    secSchedule: "Régime d'exploitation", secOptions: "Options",
    secForced: "Modèle imposé", secForcedNote: "modifier ces champs bascule en mode imposé",
    fProjectName: "Nom du projet", fProjectNo: "N° de projet",
    fAvgDSP: "Production moy. (base sèche)", fAvgDSPh: "Matière sèche produite par jour",
    fFeedDS: "Siccité alimentation Xs(0)", fFeedDSh: "0,15 = 15 % MS",
    fProductDS: "Siccité produit Xs(8)", fProductDSh: "0,92 = 92 % MS",
    fSludgeTemp: "Température boue Ts(0)",
    fDPerW: "Jours par semaine", fHPerD: "Heures par jour",
    fMinTrain: "Nb de trains minimum", fSiteElev: "Altitude du site",
    fPreheater: "Pré-chauffeur d'air", onSvc: "En service", offSvc: "Hors service",
    fPreheaterH: "Récupère la chaleur de l'air extrait (flux 7→8)",
    fCakeRT: "Rétention silo gâteau",
    fModel: "Modèle sécheur", fTrains: "Nombre de trains",

    secDryAir: "Air de séchage", secDryAirNote: "cœur du modèle",
    fDpt: "Pt de rosée air 7 (DPT)", fDptH: "Note 2 · doit rester > 60 °C, sinon l'humidité n'est pas extraite",
    fAirT0: "Temp. air 0 (entrée ZC)", fAirT0h: "Note 3 · pilote le débit de circulation ZC",
    fDT5: "ΔT air 5 (Ta − DPT)", fDT5h: "Note 3",
    fAirT12: "Temp. air 12 (entrée ZF)", fAirT12h: "Note 4",
    fDT17: "ΔT air 17 (Ta − DPT)", fDT17h: "Note 4",
    fAirT8: "Temp. air 8 (sortie HEX)", fAirT8h: "Note 7 · doit être > DPT air 7",
    fAirT9: "Temp. air 9 (sortie condenseur)",
    secSludgeBelt: "Boue & bandes",
    fMC4: "Siccité fin de ZC", fMC4h: "Note 1 · humidité (0,55 → 45 % MS). Règle le partage de charge ZC/ZF (viser un ratio évap. ≈ 2:1)",
    fBL: "Charge bande ZC", fBLh: "Note 5 · fixe la vitesse de bande haute",
    fRT: "Temps de séjour total", fRTh: "Note 6 · fixe la vitesse de bande basse",
    secLosses: "Pertes thermiques",
    fWzHL: "Perte unitaire ZC", fEzHL: "Perte unitaire ZF",
    fPhHL: "Perte pré-chauffeur", fToHL: "Perte chauffe-huile",
    secFluids: "Circuits eau & huile",
    fTw0: "Eau de refroidissement Tw(0)", fTw1: "Condensat Tw(1)",
    fO0: "Huile départ chauffe (O0)", fO1: "Huile retour chauffe (O5)",
    fO2: "Huile vers HEX ZF (O2)", fO3: "Huile retour HEX ZF (O3)",

    equipNote: "Ces valeurs décrivent la géométrie du lit de boue passe par passe. Elles sont propres à la technologie et changent rarement : ne les modifiez qu'avec des données d'essai.",
    gNoodleDia: "Diamètre spaghetti", gNoodleDen: "Masse volumique boue humide",
    gBeltOAR: "Taux d'ouverture bande", gSludgeSAR: "Surface boue exposée à l'air",
    gSludgeOAR: "Surface libre du lit", gSludgePR: "Taux de compacité (packing)",
    secFans: "Ventilateurs",
    fSfFlow: "Coef. sécurité débit", fSfPress: "Coef. sécurité pression",
    fEff: "Rendement ventilateur", fPf: "Facteur de puissance",
    fDpNoHex: "ΔP air séchage · sans HEX", fDpHex: "ΔP air séchage · avec HEX",
    fDpWz: "ΔP circulation ZC", fDpEz: "ΔP circulation ZF",
    secLimits: "Limites de conception", secLimitsNote: "valeurs de contrôle",
    fMaxVwz: "Vitesse air max ZC", fMaxVez: "Vitesse air max ZF",
    fMaxELwz: "Charge évap. max ZC", fMaxELez: "Charge évap. max ZF",
    fMaxEFwz: "Flux évap. max ZC", fMaxEFez: "Flux évap. max ZF",
    fMaxBLez: "Charge bande max ZF", fMaxThick: "Épaisseur lit max",
    fMaxNozzle: "Charge max par buse",

    sModel: "Modèle", sTrains: "Trains", sWetPerTrain: "Boue humide / train",
    sCapacity: "Capacité modèle", sEvapTotal: "Évaporation totale",
    sHeatInput: "Apport thermique", sSpecific: "Conso. spécifique", sRatio: "Ratio évap. ZC/ZF",
    limitsTitle: "Contrôle des limites de conception", conform: "conformes",
    thCriterion: "Critère", thValue: "Valeur", thLimit: "Limite", thUnit: "Unité", thState: "État",
    ok: "OK", bad: "HORS LIMITE",
    basisTitle: "Base de dimensionnement", thQuantity: "Grandeur", thTotal: "Total", thPerTrain: "Par train",
    rDS: "Débit MS (kg/h)", rWS: "Débit boue humide (kg/h)", rProd: "Débit produit sec (kg/h)", rEvap: "Charge d'évaporation (kg/h)",
    energyTitle: "Énergie (par train)", thItem: "Poste",
    eHexWz: "Capacité HEX zone chaude", eHexEz: "Capacité HEX zone finale",
    eLossWz: "Perte thermique ZC", eLossEz: "Perte thermique ZF",
    eProcess: "Apport procédé", eBurner: "Apport au brûleur",

    lEvapLwz: "Charge évap. bande ZC", lFluxWz: "Flux évap. ZC",
    lBeltLez: "Charge bande inférieure ZF", lEvapLez: "Charge évap. bande ZF",
    lFluxEz: "Flux évap. ZF", lNozzle: "Charge boue par buse",
    lThick: "Épaisseur lit bande inf.", lVwz: "Vitesse air superficielle ZC", lVez: "Vitesse air superficielle ZF",
    fixEvapWz: "↑ siccité fin ZC, ou +1 train",
    fixFluxWz: "↑ charge bande ZC, ou ↑ siccité fin ZC",
    fixBeltEz: "machine plus grande, ou +1 train",
    fixEvapEz: "↓ siccité fin ZC, ou +1 train",
    fixFluxEz: "↑ temps de séjour, ou ↓ siccité fin ZC",
    fixNozzle: "machine plus grande, ou +1 train",
    fixThick: "↓ temps de séjour, ou machine plus grande",
    fixVwz: "↑ temp. air 0, ou ↓ ΔT air 5",
    fixVezHigh: "↑ temp. air 12, ou ↓ ΔT air 17",
    fixVezLow: "↓ temp. air 12, ou ↑ ΔT air 17",

    sludgeStreams: "Flux de boue (0 → 8)",
    airWZ: "Flux d'air · zone chaude & refroidisseur",
    airEZ: "Flux d'air · pré-chauffeur & zone finale",
    oilStreams: "Huile thermique (0 → 8)", condTitle: "Condenseur (eau)",
    thIn: "Entrée", thOut: "Sortie",
    rWetFlow: "Débit boue humide", rDryFlow: "Débit matière sèche", rDryness: "Siccité",
    rMoisture: "Humidité", rTemp: "Température", rEnth: "Enthalpie", rEnergy: "Flux d'énergie",
    rVolFlow: "Débit volumique", rDryAir: "Débit air sec", rVapour: "Débit vapeur H₂O",
    rAbsHum: "Humidité absolue", rDewPt: "Point de rosée", rMassFlow: "Débit massique",

    beltTitle: "Exploitation des bandes",
    cWzBelt: "Bande ZC", cEzTop: "Bande sup. ZF", cEzBot: "Bande inf. ZF",
    rBeltW: "Largeur de bande", rBeltL: "Longueur de bande", rBeltA: "Surface de bande",
    rBeltV: "Vitesse de bande", rRT: "Temps de séjour", rThick: "Épaisseur du lit", rPoros: "Facteur de porosité",
    htTitle: "Transfert de chaleur par passe",
    rPassA: "Surface de passe", rAirDen: "Masse vol. air", rKinVis: "Viscosité cinématique",
    rPr: "Nombre de Prandtl", rVsup: "Vitesse air superficielle", rVbelt: "Vitesse à travers bande",
    rVsludge: "Vitesse à travers boue", rRe: "Nombre de Reynolds", rReC: "Reynolds corrigé",
    rNu: "Nombre de Nusselt", rK: "Coef. transfert k", rKA: "k × A", rSf: "Coef. sécurité k×A",
    htNote: "Le coefficient de sécurité compare le k×A géométrique de chaque passe au k×A moyen exigé par le bilan thermique. Une valeur > 1 signifie que la passe dispose d'une réserve de surface d'échange.",

    fansTitle: "Dimensionnement des ventilateurs",
    fanDry: "air séchage", fanWz: "circ. ZC", fanEz: "circ. ZF", fanVac: "vide",
    rNfans: "Nb par sécheur", rOpFlow: "Débit en service", rSfFlow: "Coef. sécurité débit",
    rDsgnFlow: "Débit de conception", rOpP: "ΔP en service", rDsgnP: "ΔP de conception",
    rEffi: "Rendement", rFanKW: "Puissance ventilateur", rMotKW: "Puissance moteur calc.",
    rMotHP: "Moteur retenu", rCons: "Consommation",
    heaterTitle: "Chauffe-huile thermique",
    rNeed: "Besoin par train", rHModel: "Modèle retenu", rHCap: "Capacité",
    rPumpWz: "Pompe huile ZC", rPumpEz: "Pompe huile ZF", rBurner: "Brûleur",
    rFlowWz: "Débit pompe HEX ZC", rFlowEz: "Débit pompe HEX ZF",
    binTitle: "Silo de gâteau & consommations",
    rBinVol: "Volume silo requis", rCondWater: "Eau condenseur",
    rFanPower: "Puissance ventilateurs", rSpec: "Conso. spécifique",

    footer: "Modèle itératif : les températures d'air et les siccités de sortie de chaque passe sont résolues par recherche de solution imbriquée (débit d'air de circulation, puis k×A moyen) jusqu'à atteindre la siccité cible en fin de zone chaude et la température d'air consigne. Les résultats sont exprimés par train.",

    repTitle: "Rapport de dimensionnement", repProject: "Projet", repNo: "N° projet",
    repDate: "Date", repMode: "Mode de calcul", repPrint: "Imprimer / Enregistrer en PDF",
    repDesignBasis: "Données de base", repSetpoints: "Consignes",
    repGenerated: "Document généré par Biocon",

    dgWZ: "ZONE CHAUDE (ZC)", dgEZ: "ZONE FINALE (ZF)",
    dgAirTreat: "TRAITEMENT AIR SÉCHAGE", dgOil: "HUILE THERMIQUE", dgEvap: "CHARGE D'ÉVAPORATION",
    dgPass: "Passe", dgFeed: "Boue", dgProduct: "Produit", dgDS: "MS",
    dgIn: "entrée", dgOut: "sortie", dgExtract: "extrait", dgCond: "condenseur", dgRecycl: "recyclé",
    dgCondWater: "Eau cond.", dgHexWz: "HEX ZC", dgHexEz: "HEX ZF", dgHeater: "Chauffe", dgNeed: "Besoin",
    dgTotal: "Total", dgWarmZone: "Zone chaude", dgEndZone: "Zone finale", dgRatio: "Ratio ZC/ZF",
    dgTarget: "(cible ≈ 2)", dgSelected: "MODÈLE RETENU", dgTrains: "train(s)",
    dgDepositors: "distributeurs", dgNozzles: "buses", dgDew: "pr",
    passWZ: "ZC", passEZ: "ZF",
    uKgD: "kg/j", uDays: "j",
    beltNote: (tot, sp) => `Temps de séjour total = ${tot} min (consigne : ${sp} min). Si le temps de séjour de la bande inférieure devient négatif, réduisez la charge de bande ZC ou augmentez le temps de séjour total.`,
  },

  en: {
    appSub: "belt dryer sizing",
    appTag: "Mass & heat balance · 4-pass warm zone + 4-pass end zone · pre-heater, condenser, thermal oil",
    runAuto: "Pre-size (auto)", runUser: "Compute · selected model",
    computing: "Computing…", reset: "Reset",
    save: "Save", load: "Load", report: "PDF report",
    langBtn: "FR", langTitle: "Passer en français",
    errTitle: "Calculation failed.",
    loadErr: "Project file unreadable or incompatible.",
    loadOk: "Project loaded — run the calculation again.",
    savedOk: "Project saved.",
    reportBlocked: "The print window was blocked: the report was downloaded as HTML. Open it, then print to PDF.",
    noRunTitle: "No calculation yet",
    noRunBody: "Fill in tabs 1 to 3, then run “Pre-size” to let the tool select the dryer model, or “Selected model” to check a given machine.",
    reportNeedsRun: "Run a calculation first to produce a report.",
    tabBasis: "1 · Design basis", tabSetpoints: "2 · Setpoints", tabEquip: "3 · Equipment parameters",
    tabSummary: "Summary", tabBalance: "Mass & heat balance",
    tabBelt: "Belts & heat transfer", tabEquipment: "Fans & heater",
    modeAuto: "Automatic pre-selection", modeUser: "Selected model",
    liveOn: "auto-update", liveUpdating: "recomputing…",
    modeLabel: "Mode:",

    secProject: "Project", secLoad: "Sludge load", secLoadNote: "primary inputs",
    secSchedule: "Operating schedule", secOptions: "Options",
    secForced: "Selected model", secForcedNote: "editing these switches to selected-model mode",
    fProjectName: "Project name", fProjectNo: "Project number",
    fAvgDSP: "Avg. daily production (dry)", fAvgDSPh: "Dry solids produced per day",
    fFeedDS: "Feed dry solids Xs(0)", fFeedDSh: "0.15 = 15 % DS",
    fProductDS: "Product dry solids Xs(8)", fProductDSh: "0.92 = 92 % DS",
    fSludgeTemp: "Sludge temperature Ts(0)",
    fDPerW: "Days per week", fHPerD: "Hours per day",
    fMinTrain: "Minimum train number", fSiteElev: "Site elevation",
    fPreheater: "Air pre-heater", onSvc: "In service", offSvc: "Out of service",
    fPreheaterH: "Recovers heat from exhaust air (streams 7→8)",
    fCakeRT: "Cake bin retention time",
    fModel: "Dryer model", fTrains: "Number of trains",

    secDryAir: "Drying air", secDryAirNote: "core of the model",
    fDpt: "Dew point air 7 (DPT)", fDptH: "Note 2 · must stay > 60 °C, otherwise moisture is not removed",
    fAirT0: "Air temp. 0 (WZ inlet)", fAirT0h: "Note 3 · drives WZ circulation airflow",
    fDT5: "ΔT air 5 (Ta − DPT)", fDT5h: "Note 3",
    fAirT12: "Air temp. 12 (EZ inlet)", fAirT12h: "Note 4",
    fDT17: "ΔT air 17 (Ta − DPT)", fDT17h: "Note 4",
    fAirT8: "Air temp. 8 (HEX outlet)", fAirT8h: "Note 7 · must exceed dew point of air 7",
    fAirT9: "Air temp. 9 (condenser outlet)",
    secSludgeBelt: "Sludge & belts",
    fMC4: "Moisture at end of WZ", fMC4h: "Note 1 · moisture (0.55 → 45 % DS). Sets the WZ/EZ load split (target evap. ratio ≈ 2:1)",
    fBL: "WZ unit belt load", fBLh: "Note 5 · sets the top belt speed",
    fRT: "Total retention time", fRTh: "Note 6 · sets the bottom belt speed",
    secLosses: "Heat losses",
    fWzHL: "WZ unit heat loss", fEzHL: "EZ unit heat loss",
    fPhHL: "Pre-heater loss", fToHL: "Thermal oil heater loss",
    secFluids: "Water & oil circuits",
    fTw0: "Cooling water Tw(0)", fTw1: "Condensate Tw(1)",
    fO0: "Oil supply from heater (O0)", fO1: "Oil return to heater (O5)",
    fO2: "Oil to EZ HEX (O2)", fO3: "Oil from EZ HEX (O3)",

    equipNote: "These values describe the sludge bed geometry pass by pass. They are technology-specific and rarely change: only modify them with pilot data.",
    gNoodleDia: "Sludge noodle diameter", gNoodleDen: "Wet sludge density",
    gBeltOAR: "% open area on belt", gSludgeSAR: "% sludge surface exposed to air",
    gSludgeOAR: "Open superficial area of sludge", gSludgePR: "Packing ratio",
    secFans: "Fans",
    fSfFlow: "Airflow safety factor", fSfPress: "Pressure safety factor",
    fEff: "Fan efficiency", fPf: "Power factor",
    fDpNoHex: "ΔP drying air · without HEX", fDpHex: "ΔP drying air · with HEX",
    fDpWz: "ΔP WZ circulation", fDpEz: "ΔP EZ circulation",
    secLimits: "Design limits", secLimitsNote: "check values",
    fMaxVwz: "Max. air velocity WZ", fMaxVez: "Max. air velocity EZ",
    fMaxELwz: "Max. evap. load WZ", fMaxELez: "Max. evap. load EZ",
    fMaxEFwz: "Max. evap. flux WZ", fMaxEFez: "Max. evap. flux EZ",
    fMaxBLez: "Max. belt load EZ", fMaxThick: "Max. bed thickness",
    fMaxNozzle: "Max. load per nozzle",

    sModel: "Model", sTrains: "Trains", sWetPerTrain: "Wet sludge / train",
    sCapacity: "Model capacity", sEvapTotal: "Total evaporation",
    sHeatInput: "Heat input", sSpecific: "Specific consumption", sRatio: "Evap. ratio WZ/EZ",
    limitsTitle: "Design limit check", conform: "within limits",
    thCriterion: "Criterion", thValue: "Value", thLimit: "Limit", thUnit: "Unit", thState: "Status",
    ok: "OK", bad: "OUT OF LIMIT",
    basisTitle: "Design basis", thQuantity: "Quantity", thTotal: "Total", thPerTrain: "Per train",
    rDS: "Dry solids flow (kg/h)", rWS: "Wet sludge flow (kg/h)", rProd: "Dry product flow (kg/h)", rEvap: "Evaporation load (kg/h)",
    energyTitle: "Energy (per train)", thItem: "Item",
    eHexWz: "Warm zone HEX capacity", eHexEz: "End zone HEX capacity",
    eLossWz: "WZ heat loss", eLossEz: "EZ heat loss",
    eProcess: "Process heat input", eBurner: "Burner heat input",

    lEvapLwz: "WZ belt evap. load", lFluxWz: "WZ evap. flux",
    lBeltLez: "EZ bottom belt load", lEvapLez: "EZ belt evap. load",
    lFluxEz: "EZ evap. flux", lNozzle: "Wet sludge load per nozzle",
    lThick: "Bottom belt bed thickness", lVwz: "WZ superficial air velocity", lVez: "EZ superficial air velocity",
    fixEvapWz: "↑ WZ-end moisture, or +1 train",
    fixFluxWz: "↑ WZ belt load, or ↑ WZ-end moisture",
    fixBeltEz: "larger model, or +1 train",
    fixEvapEz: "↓ WZ-end moisture, or +1 train",
    fixFluxEz: "↑ retention time, or ↓ WZ-end moisture",
    fixNozzle: "larger model, or +1 train",
    fixThick: "↓ retention time, or larger model",
    fixVwz: "↑ air temp. 0, or ↓ ΔT air 5",
    fixVezHigh: "↑ air temp. 12, or ↓ ΔT air 17",
    fixVezLow: "↓ air temp. 12, or ↑ ΔT air 17",

    sludgeStreams: "Sludge streams (0 → 8)",
    airWZ: "Air streams · warm zone & air cooler",
    airEZ: "Air streams · pre-heater & end zone",
    oilStreams: "Thermal oil (0 → 8)", condTitle: "Condenser (water)",
    thIn: "Inlet", thOut: "Outlet",
    rWetFlow: "Wet sludge mass flow", rDryFlow: "Dry sludge mass flow", rDryness: "Dry solids",
    rMoisture: "Moisture content", rTemp: "Temperature", rEnth: "Enthalpy", rEnergy: "Energy flow",
    rVolFlow: "Volumetric flow", rDryAir: "Dry air mass flow", rVapour: "H₂O vapour mass flow",
    rAbsHum: "Absolute humidity", rDewPt: "Dew point temp.", rMassFlow: "Mass flow",

    beltTitle: "Belt operation",
    cWzBelt: "WZ belt", cEzTop: "EZ top belt", cEzBot: "EZ bottom belt",
    rBeltW: "Belt width", rBeltL: "Belt length", rBeltA: "Belt area",
    rBeltV: "Belt moving speed", rRT: "Retention time", rThick: "Sludge layer thickness", rPoros: "Sludge porosity factor",
    htTitle: "Pass heat transfer",
    rPassA: "Pass area", rAirDen: "Airflow density", rKinVis: "Kinematic viscosity",
    rPr: "Prandtl number", rVsup: "Belt superficial air vel.", rVbelt: "Air vel. through belt",
    rVsludge: "Air vel. through sludge", rRe: "Reynolds number", rReC: "Corrected Reynolds number",
    rNu: "Nusselt number", rK: "Heat transfer coeff. k", rKA: "k × A", rSf: "Safety factor on k×A",
    htNote: "The safety factor compares the geometric k×A of each pass with the average k×A required by the heat balance. A value > 1 means the pass has spare exchange surface.",

    fansTitle: "Fan design",
    fanDry: "drying air", fanWz: "WZ circ.", fanEz: "EZ circ.", fanVac: "vacuum",
    rNfans: "No. per dryer", rOpFlow: "Operating airflow", rSfFlow: "Airflow safety factor",
    rDsgnFlow: "Design airflow", rOpP: "Operating ΔP", rDsgnP: "Design ΔP",
    rEffi: "Efficiency", rFanKW: "Calculated fan capacity", rMotKW: "Calculated motor capacity",
    rMotHP: "Selected motor", rCons: "Power consumption",
    heaterTitle: "Thermal oil heater",
    rNeed: "Requirement per train", rHModel: "Selected model", rHCap: "Capacity",
    rPumpWz: "WZ oil pump", rPumpEz: "EZ oil pump", rBurner: "Burner",
    rFlowWz: "WZ HEX pump flow", rFlowEz: "EZ HEX pump flow",
    binTitle: "Cake bin & utilities",
    rBinVol: "Required bin volume", rCondWater: "Condenser water",
    rFanPower: "Total fan power", rSpec: "Specific consumption",

    footer: "Iterative model: air temperatures and outlet dry solids of each pass are solved by nested goal-seek (circulation airflow, then average k×A) until the target dry solids at the end of the warm zone and the air temperature setpoint are reached. Results are expressed per train.",

    repTitle: "Sizing report", repProject: "Project", repNo: "Project no.",
    repDate: "Date", repMode: "Calculation mode", repPrint: "Print / Save as PDF",
    repDesignBasis: "Design basis", repSetpoints: "Setpoints",
    repGenerated: "Document generated by Biocon",

    dgWZ: "WARM ZONE (WZ)", dgEZ: "END ZONE (EZ)",
    dgAirTreat: "DRYING AIR TREATMENT", dgOil: "THERMAL OIL", dgEvap: "EVAPORATION LOAD",
    dgPass: "Pass", dgFeed: "Sludge", dgProduct: "Product", dgDS: "DS",
    dgIn: "inlet", dgOut: "outlet", dgExtract: "extracted", dgCond: "condenser", dgRecycl: "recycled",
    dgCondWater: "Cond. water", dgHexWz: "WZ HEX", dgHexEz: "EZ HEX", dgHeater: "Heater", dgNeed: "Required",
    dgTotal: "Total", dgWarmZone: "Warm zone", dgEndZone: "End zone", dgRatio: "Ratio WZ/EZ",
    dgTarget: "(target ≈ 2)", dgSelected: "SELECTED MODEL", dgTrains: "train(s)",
    dgDepositors: "depositors", dgNozzles: "nozzles", dgDew: "dp",
    passWZ: "WZ", passEZ: "EZ",
    uKgD: "kg/d", uDays: "d",
    beltNote: (tot, sp) => `Total retention time = ${tot} min (setpoint: ${sp} min). If the bottom belt retention time turns negative, reduce the WZ unit belt load or increase the total retention time.`,
  },
};
